### ISSUE TITLE
Can't launch miLazyCracker

### ISSUE THREAD

**Issue by michto36** [iAmNotSuperman/miLazyCracker#2]
hi ! ;)

When i launch the script i've got the usage documentation for mfoc .. what can i do ?
( i'm using ACR-122u usb reader )

root@mypersonalplace:~/miLazyCracker/mydumps# miLazyCracker 
Usage: mfoc [-h] [-k key] [-f file] ... [-P probnum] [-T tolerance] [-O output]

  h     print this help and exit
  k     try the specified key in addition to the default keys
  f     parses a file of keys to add in addition to the default keys 
  P     number of probes per sector, instead of default of 20
  T     nonce tolerance half-range, instead of default of 20
        (i.e., 40 for the total range, in both directions)
  O     file in which the card contents will be written (REQUIRED)

Example: mfoc -O mycard.mfd
Example: mfoc -k ffffeeeedddd -O mycard.mfd
Example: mfoc -f keys.txt -O mycard.mfd
Example: mfoc -P 50 -T 30 -O mycard.mfd

This is mfoc version 0.10.7.
For more information, run: 'man mfoc'.

Thanks and good job ;)

**Comment by Germain67** [comment]
Maybe try with "../miLazyCracker.sh" if you haven't already tried.

**Comment by michto36** [comment]
it's answered me the same thing, the mfoc usage doc...

**Comment by michto36** [comment]
it's answered me the same thing, the mfoc usage doc ... :/

**Comment by michto36** [comment]
erf, i just understood why i've got wrong ... miLazyCracker uses a modified mfoc .. with a new " -D " argument... but i can't install it .. 

i've got this message when i try to exec the command "./configure" in mfoc folder.

configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."


Sorry i'm not used to play with *nix systems so sometimes i'm lacking of knowledge ;)

**Comment by Germain67** [comment]
No problem, I think you may give a try to the following commands.

To begin, try the following command
`sudo apt-get install automake autoconf`
Then try to re-run ./configure

If it still doesn't work try this :
`libtoolize --force
aclocal
autoheader
automake --force-missing --add-missing
autoconf
./configure`

I hope it will help you ;)

**Comment by michto36** [comment]
Thanks for your help i will try that soon. For the moment i found a way to use hardnested attack directly with "libnfc_crypto1_crack"  furnished in miLazyCracker package, so it's working =)

Thanks anyway.
